In [1]:
import numpy as np 

a = np.array([1, 2, 3])     # 1D array — like a vector
b = np.array([[1, 2, 3], [4, 5, 6]])     # 2D array — like a matrix

print(a.shape)
print(b.shape)
print(b.dtype)

(3,)
(2, 3)
int64


**Pattern 1: Boolean Masking**

Instead of writing a loop to check each element, you ask NumPy a question about the whole array at once, and it gives you back a True/False array. You then use that to filter.

In [2]:
z = np.array([10, 25, 3, 47, 8, 55, 12])

# Step 1: ask a question — get a boolean array back
mask = z > 20
print(mask)
# [False  True False  True False  True False]

# Step 2: use that mask to filter
print(z[mask])
# [25 47 55]

# You can do it in one line
print(z[z > 20])
# [25 47 55]



#Using AND and OR with masks

print(z[(z > 10) & (z < 50)])
# [25 47 12]

print(z[(z < 10) | (z > 50)])
# [3 8 55]



#MODIFY VALUES WITH MASKS
z[z > 20] = 0       # set all values above 20 to zero
print(z)
# [10  0  3  0  8  0 12]

[False  True False  True False  True False]
[25 47 55]
[25 47 55]
[25 47 12]
[ 3  8 55]
[10  0  3  0  8  0 12]


Real ML use case: cleaning sensor data. If your BMS battery voltage readings have corrupt spikes above a physical maximum, you'd do:
*voltage[voltage > 4.2] = np.nan*  # mark impossible readings as missing

**Pattern 2: Broadcasting**

Broadcasting is what happens when you do math between two arrays of different shapes — NumPy automatically "stretches" the smaller one to match the larger one, without actually copying data.

In [3]:
#Scalar and Array

z = np.array([1, 2, 3, 4, 5])
print(z * 2)

[ 2  4  6  8 10]


Now 2D and 1D Array

In [4]:
matrix = np.array([ [1, 2, 3], 
                    [4, 5, 6], 
                    [7, 8, 9]]) 
#3x3 Matrix

row = np.array([10, 20, 30])

print(matrix + row)

[[11 22 33]
 [14 25 36]
 [17 28 39]]


The most common use in ML — subtracting the mean of each row to normalise data:


In [5]:
data = np.array([[10.0, 20.0, 30.0],
                 [1.0,  2.0,  3.0],
                 [5.0,  15.0, 25.0]])

row_means = data.mean(axis=1, keepdims=True)
print(row_means)

print(data - row_means)

[[20.]
 [ 2.]
 [15.]]
[[-10.   0.  10.]
 [ -1.   0.   1.]
 [-10.   0.  10.]]


**Pattern 3: Vectorisation**

This is the habit of replacing every Python for-loop with an array operation. It's not just about cleaner code — NumPy operations run in compiled C under the hood, so vectorised code can be 100–1000x faster than a Python loop.

In [6]:
# Task: square every element and sum the result

data = np.arange(1_000_000)

# Fast vectorised NumPy
total = np.sum(data ** 2)

In [7]:
# Compute distance from origin for 10000 2D points. 
# It's a 10000×2 array — 10000 rows, 2 columns. Each row is one point with an x and y coordinate.
points = np.random.rand(10000, 2)



distances = np.sqrt(points[:, 0]**2 + points[:, 1]**2)

#Step 1: `points[:, 0]` — grab the entire first column (all x values). The `:` means "every row", `0` means "column 0". So this pulls out all 10000 x coordinates as a 1D array

#Step 2: `points[:, 1]` — grab the entire second column (all y values)